### ISSUE TITLE
Fading out grid

### ISSUE THREAD

**Issue by xcraftster** [libre3d/render-3d#26]
Guys, I made it up and running on Linux, works as a charm. Quick question: is that possible to make the grid fading out same like it renders the grid on thingiverse.

**Comment by jonyo** [comment]
Hey @xgridder so, I must have had notifications turned off!  If you still had this question, or anyone else did:

The short answer is there isn't anything built in. The longer answer is that yes it's Possible because you can use a different scene template if you want.

It uses a PHP file as a template to create the POVRay scene.  The part that specifically creates the grid using that library is here:

https://github.com/libre3d/render-3d/blob/1cb271ba2865192b45f109e18cbeb15d3864a965/src/Scenes/Pov/layout.php#L50-L62

You could play around with adding some kind of atmospheric fog or something like that, it might give a fade out appearance not sure.  If you do happen to still be looking at this and happen to find a solution, feel free to share here we might add it to the docs.  I'm going to go ahead and close, if you have further followup question feel free to reopen.
